site_name: Blind75py

theme:
  name: dracula
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  # palette:
  #   - scheme: slate
  #     primary: '#44475a' # Dracula's background color
  #     accent: '#ff79c6' # Dracula's pink accent
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs
    - content.code.annotate
# extra_css:
#   - assets/css/custom.css

nav:
  - Home: index.md
  - Arrays & Hashing:
    - Two Sum: arrays_hashing/two_sum.md
    - Best Time to Buy and Sell Stock: arrays_hashing/best_time_to_buy_and_sell_stock.md
    - Contains Duplicate: contains_duplicate.md
    - Product of Array Except Self: product_of_array_except_self.md
    - Valid Anagram: valid_anagram.md
    - Group Anagrams: group_anagrams.md
    - Longest Palindrome: longest_palindrome.md
  - Two Pointers:
    - 3Sum: 3sum.md
    - Container With Most Water: container_with_most_water.md
    - Valid Palindrome: valid_palindrome.md
    - Valid Palindrome II: valid_palindrome_ii.md
    - Linked List Cycle: linked_list_cycle.md
    - Linked List Cycle II: linked_list_cycle_ii.md
    - Find the Duplicate Number: find_the_duplicate_number.md
    - Happy Number: happy_number.md
  - Sliding Window:
    - Longest Substring Without Repeating Characters: longest_substring_without_repeating_characters.md
    - Longest Repeating Character Replacement: longest_repeating_character_replacement.md
    - Minimum Window Substring: minimum_window_substring.md
    - Permutation in String: permutation_in_string.md
  - Stack:
    - Valid Parentheses: valid_parentheses.md
  - Binary Search:
    - Find Minimum in Rotated Sorted Array: find_minimum_in_rotated_sorted_array.md
    - Search in Rotated Sorted Array: search_in_rotated_sorted_array.md
  - Linked Lists:
    - Merge Two Sorted Lists: merge_two_sorted_lists.md
    - Reverse Linked List: reverse_linked_list.md
    - Reorder List: reorder_list.md
    - Remove Nth Node From End of List: remove_nth_node_from_end_of_list.md
    - Merge K Sorted Lists: merge_k_sorted_lists.md
    - Swap Nodes in Pairs: swap_nodes_in_pairs.md
    - Add Two Numbers: add_two_numbers.md
    - Remove Duplicates from Sorted List: remove_duplicates_from_sorted_list.md
    - Remove Duplicates from Sorted List II: remove_duplicates_from_sorted_list_ii.md
  - Trees:
    - Invert Binary Tree: invert_binary_tree.md
    - Maximum Depth of Binary Tree: maximum_depth_of_binary_tree.md
    - Balanced Binary Tree: balanced_binary_tree.md
    - Same Tree: same_tree.md
    - Subtree of Another Tree: subtree_of_another_tree.md
    - Lowest Common Ancestor of a Binary Search Tree: lowest_common_ancestor_of_a_binary_search_tree.md
    - Binary Tree Level Order Traversal: binary_tree_level_order_traversal.md
    - Validate Binary Search Tree: validate_binary_search_tree.md
    - Kth Smallest Element in a BST: kth_smallest_element_in_a_bst.md
    - Construct Binary Tree from Preorder and Inorder Traversal: construct_binary_tree_from_preorder_and_inorder_traversal.md
    - Binary Tree Right Side View: binary_tree_right_side_view.md
    - Count Good Nodes in Binary Tree: count_good_nodes_in_binary_tree.md
    - Lowest Common Ancestor of a Binary Tree: lowest_common_ancestor_of_a_binary_tree.md
  - Tries:
    - Implement Trie (Prefix Tree): implement_trie_prefix_tree.md
    - Design Add and Search Words Data Structure: design_add_and_search_words_data_structure.md
  - Dynamic Programming:
    - Climbing Stairs: climbing_stairs.md
    - Coin Change: coin_change.md
    - Longest Increasing Subsequence: longest_increasing_subsequence.md
    - Longest Common Subsequence: longest_common_subsequence.md
    - Word Break: word_break.md
    - House Robber: house_robber.md
    - House Robber II: house_robber_ii.md
    - Decode Ways: decode_ways.md
    - Unique Paths: unique_paths.md
    - Jump Game: jump_game.md
    - Longest Palindromic Substring: longest_palindromic_substring.md
    - Palindromic Substrings: palindromic_substrings.md
    - Maximum Subarray: maximum_subarray.md
    - Maximum Product Subarray: maximum_product_subarray.md
  - Graphs:
    - Clone Graph: clone_graph.md
    - Course Schedule: course_schedule.md
    - Pacific Atlantic Water Flow: pacific_atlantic_water_flow.md
    - Number of Islands: number_of_islands.md
  - Intervals:
    - Merge Intervals: merge_intervals.md
    - Insert Interval: insert_interval.md
    - Meeting Rooms: meeting_rooms.md
    - Meeting Rooms II: meeting_rooms_ii.md
    - Non-overlapping Intervals: non_overlapping_intervals.md
  - Bit Manipulation:
    - Sum of Two Integers: sum_of_two_integers.md
    - Number of 1 Bits: number_of_1_bits.md
    - Counting Bits: counting_bits.md
    - Missing Number: missing_number.md
    - Reverse Bits: reverse_bits.md
  - Backtracking:
    - Combination Sum: combination_sum.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html